export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const FETCH_PUBLIC_FILES_SUCCESS = 'FETCH_PUBLIC_FILES_SUCCESS';
export const FETCH_PUBLIC_FILE_URL_SUCCESS = 'FETCH_PUBLIC_FILE_URL_SUCCESS';
